spring:
  application:
    name: driver-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/springclouddb
      database: springclouddb
server:
  port: 8080
eureka:
  client:
    enabled: ${ENABLED_EUREKA:false}
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/