spring:
  application:
    name: driver-service
  data:
    mongodb:
      uri: mongodb://admin:senha123@ds141208.mlab.com:41208/springclouddb
      database: springclouddb
server:
  port: 8080
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/