spring:
  application:
    name: driver-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:admin}:${MONGODB_PASSWORD:senha123}@${MONGODB_HOST:ds141208.mlab.com}:${MONGODB_PORT:41208}/${MONGODB_DATABASE:springclouddb}
      database: ${MONGODB_DATABASE:springclouddb}
server:
  port: 8080
eureka:
  client:
    enabled: ${ENABLED_EUREKA:false}
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/